apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/account-service

patchesStrategicMerge:
- account-service-resources-patch.yaml

configMapGenerator:
  name: account-service-config
  files:
  -./configmaps/ account-service-configmap.yaml

images:
- name: docker.io/adrianomoretti/account-service
  newTag: latest
