apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/payment-service


configMapGenerator:
- name: payment-service-config
  literals:
    - APP_NAME=payment-service
    - APP_ENV=staging
    - LOG_LEVEL=info
  options:
    disableNameSuffixHash: true

images:
- name: docker.io/adrianomoretti/payment-service
  newTag: latest
