apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service  # nome do Deployment exato
spec:
  template:
    spec:
      containers:
      - name: payment-service
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
