apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-
namespace: prod

images:
  - name: docker.io/adrianomoretti/fintech-devsecops-app
    newTag: "prod"

configMapGenerator:
  - name: prod-config
    files:
      - ../../base/configmaps.yaml

secretGenerator:
  - name: prod-secrets
    literals:
      - DOCKER_USER=adrianomoretti
      - DOCKER_PASS=********
    type: kubernetes.io/basic-auth
