apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/payment-service

patchesStrategicMerge:
- payment-service--resources-patch.yaml

images:
- name: docker.io/adrianomoretti/payment-service
  newTag: latest

generatorOptions:
  disableNameSuffixHash: true
