apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../../base/user-service

configMapGenerator:
- files:
  - ./configmaps/user-service-configmap.yaml
  name: staging-config

images:
- name: docker.io/adrianomoretti/user-service
  newTag: latest

generatorOptions:
  disableNameSuffixHash: true
