apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/user-service

patchesStrategicMerge:
- user-service--resources-patch.yaml

configMapGenerator:
- name: user-service-config
  files:
  - ./configmaps/user-service-configmap.yaml

images:
- name: docker.io/adrianomoretti/user-service
  newTag: latest
