
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/user-service

configMapGenerator:
- name: user-service-config
  literals:
    - APP_NAME=user-service
    - APP_ENV=dev
    - LOG_LEVEL=info
  options:
    disableNameSuffixHash: true

images:
- name: docker.io/adrianomoretti/user-service
  newTag: latest
