apiVersion: v1
kind: Service
metadata:
  name: investment-service-service
spec:
  type: NodePort
  selector:
    app: investment-service
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30008
