apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-service
  labels:
    app: investment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: investment-service
  template:
    metadata:
      labels:
        app: investment-service
    spec:
      containers:
      - name: investment-service
        image: docker.io/adrianomoretti/fintech-devsecops-app:investment-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: investment-service-config
                key: APP_NAME
          - name: APP_ENV
            valueFrom:
              configMapKeyRef:
                name: investment-service-config
                key: APP_ENV
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: investment-service-config
                key: LOG_LEVEL
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: investment-service-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: investment-service-secret
                key: DB_PASSWORD
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: investment-service-secret
                key: API_KEY
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: docker-hub
