apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../../base/api-gateway

configMapGenerator:
- files:
  - ./configmaps/api-gateway-configmap.yaml
  name: dev-config

images:
- name: docker.io/adrianomoretti/api-gateway
  newTag: latest

generatorOptions:
  disableNameSuffixHash: true
