apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/api-gatewa

patchesStrategicMerge:
- api-gateway--resources-patch.yaml

configMapGenerator:
- name: api-gateway-config
  files:
  - ./configmaps/api-gateway-configmap.yaml

images:
- name: docker.io/adrianomoretti/api-gateway
  newTag: latest
