apiVersion: v1
kind: Service
metadata:
  name: reporting-service-service
spec:
  type: NodePort
  selector:
    app: reporting-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30012
