apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - account-service
  - api-gateway
  - auth-service
  - card-service
  - fraud-detection-service
  - investment-service
  - kyc-service
  - loan-service
  - monitoring-service
  - notification-service
  - payment-service
  - reporting-service
  - transaction-service
  - user-service
  - wallet-service
