apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- account-service
- payment-service
- user-service
- auth-service
- api-gateway

configMapGenerator:
- name: account-service-config
  files:
  - configmaps/account-service-configmap.yaml
- name: payment-service-config
  files:
  - configmaps/payment-service-configmap.yaml
- name: user-service-config
  files:
  - configmaps/user-service-configmap.yaml
- name: auth-service-config
  files:
  - configmaps/auth-service-configmap.yaml
- name: api-gateway-config
  files:
  - configmaps/api-gateway-configmap.yaml

generatorOptions:
  disableNameSuffixHash: true
