apiVersion: v1
kind: Secret
metadata:
  name: fraud-detection-service-secret
type: Opaque
stringData:
  DB_USER: "fraud-detection-service_user"
  DB_PASSWORD: "ChangeMe123!"
  API_KEY: "ChangeMeAPIKey"
