apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# referência à base de deployments
resources:
  - ../../base

# adiciona ConfigMaps específicos do staging
configMapGenerator:\n      - ./configmaps/account-service-configmap.yaml\n      - ./configmaps/api-gateway-configmap.yaml\n      - ./configmaps/auth-service-configmap.yaml\n      - ./configmaps/card-service-configmap.yaml\n      - ./configmaps/fraud-detection-service-configmap.yaml\n      - ./configmaps/investment-service-configmap.yaml\n      - ./configmaps/kyc-service-configmap.yaml\n      - ./configmaps/loan-service-configmap.yaml\n      - ./configmaps/monitoring-service-configmap.yaml\n      - ./configmaps/notification-service-configmap.yaml\n      - ./configmaps/payment-service-configmap.yaml\n      - ./configmaps/reporting-service-configmap.yaml\n      - ./configmaps/transaction-service-configmap.yaml\n      - ./configmaps/user-service-configmap.yaml\n      - ./configmaps/wallet-service-configmap.yaml

# usa secrets já criados no cluster
secretGenerator:
  - name: docker.io/adrianomoretti/fintech-devsecops-app
    newTag: latest

generatorOptions:
  disableNameSuffixHash: true
